baseURL = "/"
languageCode = "en-us"
title = "Ricets"
theme = "the-theme"


[taxonomies]
  category = "categories"
  dieta = "dieta"
  livello = "livello"
  tempo = "tempo"

[permalinks]
  livello = "/:section/:slug/"

[menu]

[[menu.main]]
name = "about"
identifier = "about"
url = "/about/"
weight = 1

[[menu.main]]
name = "contact"
identifier = "contact"
url = "/contact/"
weight = 2

[[menu.footer]]
name = "privacy"
url = "privacy/"
weight = 1

[[menu.difficulty]]
name = "facile"
url = "/livello/facile"
weight = 1

[[menu.difficulty]]
name = "medio"
url = "/livello/medio"
weight = 2

[[menu.difficulty]]
name = "difficile"
url = "/livello/difficile"
weight = 3

[[menu.difficulty]]
name = "esperto"
url = "/livello/esperto"
weight = 4

[[menu.difficulty]]
name = "super nonna"
url = "/livello/super-nonna"
weight = 5