baseURL = "/"
languageCode = "en-us"
title = "Ricets"
theme = "the-theme"
paginate = 2

[taxonomies]
  category = "categories"
  dieta = "dieta"
  livello = "livello"
  tempo = "tempo"

[menu]

[[menu.main]]
name = "about"
identifier = "about"
url = "/about/"
weight = 1

[[menu.main]]
name = "contact"
identifier = "contact"
url = "/contact/"
weight = 2

[[menu.footer]]
name = "privacy"
url = "/privacy/"
weight = 1

[params]
[[livello]]
sortByWeight = true
[[dieta]]
sortByWeight = false