baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ricets"
theme = "the-theme"


[taxonomies]
  category = "categories"
  dieta = "dieta"
  livello = "livello"
  tempo = "tempo"






[[menu.main]]
name = "CHI SONO"
url = "about/"
weight = 1

[[menu.main]]
name = "CONTATTI"
url = "contact/"
weight = 2
