backend:
  name: git-gateway
  # repo: Korka13/Korka13.github.io
  branch: master
  site_domain: youthful-kare-33d160.netlify.com

display_url: https://youthful-kare-33d160.netlify.com

publish_mode: editorial_workflow


# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "ricetta" # Used in routes, e.g., /admin/collections/blog
    label: "Ricetta" # Used in the UI
    folder: "content/ricetta" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Image", name: "image", widget: "image"}
      - label: "Category"
        name: "categories"
        widget: "select"
        options: ["primi", "secondi", "antipasti", "dolci", "estere"]
      - label: "Livello"
        name: "livello"
        widget: "select"
        options:
            - { label: "facile", value: [01 facile] }
            - { label: "medio", value: [02 medio] }
            - { label: "difficile", value: [03 difficile] }
            - { label: "esperto", value: [04 esperto] }
            - { label: "super nonna", value: [05 super nonna] }
      - {
          label: 'Dieta',
          name: 'dieta',
          widget: 'select',
          options: ['vegetariana', 'vegana', 'senza glutine'],
          multiple: true,
        }
      - label: "Porzioni"
        name: "porzioni"
        widget: "number"
        valueType: "int"
        default: 4
      - label: "Tempo"
        name: "tempo"
        widget: "list"
      - {label: "Ingredienti", name: "ingredienti", widget: "list"}
      - {label: "Keywords", name: "keywords", widget: "list"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    delete: false
    files:
      - file: "content/about.md"
        label: "Chi Siamo"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/privacy.md"
        label: "Privacy Page"
        name: "privacy"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
